app/src/main/java/com/example/triptracker/MainActivity.kt
app/src/main/java/com/example/triptracker/view/LoginScreen.kt
app/src/main/java/com/example/triptracker/view/Navigation.kt
app/src/main/java/com/example/triptracker/view/NavigationBar.kt

This PR will allow user to have the finally navigate through the main app destinations/tabs.
Here is a quick overview of what was done :
- In `Navigation.kt`, added a isLoggedIn status tracking since it influences the navigation behavior.
- In `MainActivity.kt`, added a listener to isLoggedIn such that when the boolean is false, it displays the LoggingScreen, otherwise we have the classic app content with the bottom navigation bar.
- Defined a scaffold so that the navigation bar appears over each of the four main tabs.
- Adjusted the padding in order to prevent the navigation bar from being displayed above the tabs and from hiding content.
Visualization of the implementations:
https://github.com/EPFL-SwEnt-2024-LaStartUp/TripTracker/assets/100281310/c566d16d-57da-4ce0-bfb7-ce6e4ffdf19e …

Implement the bottom navigation bar redirection

---

app/src/main/java/com/example/triptracker/view/HomeScreen.kt
app/src/main/java/com/example/triptracker/view/map/MapElements.kt
app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
app/src/main/java/com/example/triptracker/view/theme/Color.kt

This PR will adress the issues from #31 and also refactor some code so that the two GoogleMaps screens are similar and in harmony with the figma design.
Some code common to both screens was also refactored : 
- Colors were updated and put in the global theme of the app
- Font was updated to match the Figma design
- The center location button was updated so that they are both at the same place and only displayed if the location permissions are enabled
<image src="https://github.com/EPFL-SwEnt-2024-LaStartUp/TripTracker/assets/79469048/b04e5540-5907-4fc3-aec5-c311816e27ee" width="312">
<image src="https://github.com/EPFL-SwEnt-2024-LaStartUp/TripTracker/assets/79469048/2eae171b-ab07-4706-84ba-41982384b679" width="312">

Smooth camera navigation map overview and refactor code of maps screens

---

app/src/main/java/com/example/triptracker/view/HomeScreen.kt
app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt

This PR will allow the user to search for an itinerary based on its title.
1. For now, filters only by Itinerary Title.
2. In the "search view", it displays a list of `ItineraryItem` which is just a clickable text element
3. Clicking on an ItineraryItem will bring you to the map for now. Later it will also display a preview of the itinerary and as soon as you press start it will show the first few pins and the route (see Figma)
4. Clicking on the back button brings you back to the home page.
5. Clicking on the "X" button clears the text field and resets the search query to default. Only problem is that it loses focus when you clear the text, not so important for now but we should change this at some point.
6. Added a few comments here and there in `HomeScreen.kt`
It Should look like this …

Implemented the Search bar in the `HomeScreen`

---

.github/workflows/build.yaml

Add new github workflow file that builds the project and creates the 
APK in the release tab of the Project.
Only triggered on push to a PR that is open (like the CI)
Additional release files are stored in the github action on successful run

Add new github workflow file that builds the project and creates the APK

---

app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt

This PR updates the UI to correctly show the itinerary when clicked on it on the map.
Itinerary boxes now have a fixed size. 
Changes are in 
1. Put the pinNames at the bottom of the box
2. Put Search for an itinerary in the middle of the search bar
This is how It looks like:

Modified `DisplayItinerary` to have fixed size Itinerary boxes

---

app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt

This PR enables the user to search Itineraries not only by their titles but also by their usernames, flame counts, and even pin names !
To filter by flame counts, simply write your inequality (e.g <=2500) and it will give all itineraries which satisfy it.
The following changes were made : 
- Modification in `HomeViewModel.kt` :  filtering the Itinerary list given search query with a given Filter (_TITLE_, _USERNAME_, _FLAME_ or _PIN_)
- DropDownMenu with Text created in `HomeScreen.kt`
- A new test has been added, leading to 81% total coverage on the home package.
- To have a cleaner UI, change "Search for an itinerary" text to "Find itineraries"
- Fixed the bug when clicking clear text button brought user back to home view. Clicking it once when search query is not empty clears the text, …

Search Bar Filter Enhancements

---

app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileFollowersScreen.kt
app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileFollowingScreen.kt
app/src/androidTest/java/com/example/triptracker/userProfile/MockUserList.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileListTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileViewModelTest.kt
app/src/main/java/com/example/triptracker/model/profile/UserProfile.kt
app/src/main/java/com/example/triptracker/model/profile/UserProfileList.kt
app/src/main/java/com/example/triptracker/model/repository/UserProfileRepository.kt
app/src/main/java/com/example/triptracker/view/profile/FriendListView.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileFollowers.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileFollowing.kt
app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt

The followers and following now match the Figma. (Another pull request will be done to add the search bar to both views) :
I also refactored some parts of the UserProfile: 
- The birthday is now stored as a string (and will be converted to a LocalDate when necessary)
- The pseudo is now renamed to username
The functions in the UserProfileViewModel handling the followers/following have been changed. There are now only two functions :
- addFollower(userProfile, follower) : function to call when userProfile starts following follower
- removeFollower(userProfile, follower) : function to call when userProfile remove follower from it's followers
The reason for this change is that it avoid useless code duplication as addFollowing(userProfile, following) was the same as doing …

Follower following screens update

---

app/src/androidTest/java/com/example/triptracker/map/MapOverviewTest.kt
app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileFollowersScreen.kt
app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileFollowingScreen.kt
app/src/androidTest/java/com/example/triptracker/userProfile/MockUserList.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileListTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileViewModelTest.kt
app/src/main/java/com/example/triptracker/MainActivity.kt
app/src/main/java/com/example/triptracker/model/location/popupState.kt
app/src/main/java/com/example/triptracker/model/profile/UserProfile.kt
app/src/main/java/com/example/triptracker/model/profile/UserProfileList.kt
app/src/main/java/com/example/triptracker/model/repository/UserProfileRepository.kt
app/src/main/java/com/example/triptracker/view/TopNavigationBar.kt
app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
app/src/main/java/com/example/triptracker/view/profile/FriendListView.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileFollowers.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileFollowing.kt
app/src/main/java/com/example/triptracker/viewmodel/MapViewModel.kt
app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt

Issue #119 is addressed by this pull request, which incorporates the UI for the profile editing window `UserProfileEditScreen.kt` based on the Figma design. Users can now edit various details such as username, name, surname, email, date of birth, and profile picture. Text fields are set up to show a red border when empty, preventing the saving of incomplete profiles. The Material3 DatePicker composable is used for selecting the date of birth. I also added a new file `TopNavigationBar.kt`, which could be useful later.
Remaining tasks include:
- Creating tests
- Checking and cleaning up text inputs for validation
- Integrating the UI into the application's navigation path

Add Profile Edit Screen UI

---

app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileEditScreenTest.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt

Associated issue: #132 
This PR adds the test coverage for `UserProfileEditScreen.kt`.

Few adjustments on UserProfileEditScreen + add 80% test coverage

---

app/src/androidTest/java/com/example/triptracker/map/AddSpotTest.kt
app/src/androidTest/java/com/example/triptracker/map/MapOverviewTest.kt
app/src/androidTest/java/com/example/triptracker/map/MapPopupTest.kt
app/src/main/java/com/example/triptracker/MainActivity.kt
app/src/main/java/com/example/triptracker/model/geocoder/NominatimApi.kt
app/src/main/java/com/example/triptracker/view/Navigation.kt
app/src/main/java/com/example/triptracker/view/NavigationBar.kt
app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
app/src/main/java/com/example/triptracker/view/map/AddSpot.kt
app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
app/src/main/java/com/example/triptracker/viewmodel/MapViewModel.kt

This PR will : 
- Fix navigation bugs when going from home to maps when clicking on a path. The camera will be centered on the selected path, display it as if it was clicked and show the pop up.
- Allow to click on an itinerary in the search bar so that it navigates directly to it's map overview.
- Navigating between home and Maps now resets the stored states and is not crashing anymore.
- Now clicking on the map in the map overview unselect the path if there was one selected and displayed in bold.
- Add spot was changed in order to match the figma design.
- Tests are fixed.
- Now clicking on the pop up of a path opens the path overview with all the spots in full screen width.
- Clicking on one of these pins opens the pin description and shows the picture.
<image src = …

Smoothing maps and record

---

app/src/androidTest/java/com/example/triptracker/map/MapPopupTest.kt
app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt

This PR fixes all tests in the home Package.
In `HomeScreen.kt`and `HomeUtils.kt`
- had to put a quite ugly test parameter for now as moving the `readyToDisplay`and `profile` to the UserProfileViewModel but it's harder than I thought and it didn't work when I tried... will still try to fix this later
82% coverage now

Home Tests All pass now

---

app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileEditScreenTest.kt
app/src/main/java/com/example/triptracker/MainActivity.kt
app/src/main/java/com/example/triptracker/model/repository/ImageRepository.kt
app/src/main/java/com/example/triptracker/view/Navigation.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileOverview.kt
app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt

This PR links the User Profile Edit Screen into the app.
Several changes were needed in different files to:
- support the save of the user profile picture to the DB by updating UserProfileViewModel
- make the navigation work
- rework a bit the UI of UserProfileOverview
- retrieve the ambiant profile,
- make the tests pass again plus add coverage for new code.

Link the User Profile Edit Screen

---

app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFriendsTest.kt
app/src/main/java/com/example/triptracker/view/profile/FriendListView.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileFollowers.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileFollowing.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileFriends.kt

Corresponding issue : #163 
The colors used in the views `UserProfileFollowers`, `UserProfileFollowing`, `UserProfileFriends` and their subview `FriendListView` are now using the Application theme and are no longer hardcoded 
I also refactored the UserProfileViewModel parameter of each of those view to userProfileViewModel instead of viewModel to make it clearer to understand along the code

Updated the colours to match the App theme

---

app/src/androidTest/java/com/example/triptracker/map/StartScreenTest.kt
app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
app/src/main/java/com/example/triptracker/view/map/MapPopups.kt

Startscreen working:
- UserImage displayed
- User name displayed
- flamecount displayed
- pins displayed
- images displayed
Next steps: implement it into the flow of the app
Tests passed with mock db, no cloud Firestore this time 
TODO: Star is black for some reason, even though one selected is outlined
EDIT:
Integrated into flow of the app
Removed preview composable
resized so images don't take up the whole screen size, same for list of pins

Map start screen

---

app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileFollowersScreen.kt
app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileFollowingScreen.kt
app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileFriendsScreen.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFollowersTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFollowingTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFriendsTest.kt
app/src/main/java/com/example/triptracker/view/profile/FriendListView.kt
app/src/main/java/com/example/triptracker/view/profile/FriendSearchBar.kt

**Corresponding issue: #152** 
This PR provides tests for the following views in the User Profile section:
- `UserProfileFollowing` : displays the accounts of people following the authenticated user
- `UserProfileFollower` : displays the accounts of the people followed by the authenticated user
- `UserProfileFriends` : enables the user to look for other people's account and start following them
Those views all relies on the following subviews that get tested as well : 
- `FriendListView` : handles the way of displaying the list of users
- `RemoveFriendButton` : is used to manage the relation with the displayed user 
- `FriendSearchBar` : is used to easily search among the displayed users based on their name, surname or username

Friend views test

---

app/build.gradle.kts
app/src/androidTest/java/com/example/triptracker/map/AddSpotCameraTest.kt
app/src/androidTest/java/com/example/triptracker/map/AddSpotTest.kt
app/src/androidTest/java/com/example/triptracker/screens/AddSpotScreen.kt
app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
app/src/androidTest/java/com/example/triptracker/screens/home/HomeViewScreen.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/triptracker/MainActivity.kt
app/src/main/java/com/example/triptracker/view/CameraPermissions.kt
app/src/main/java/com/example/triptracker/view/LoginScreen.kt
app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
app/src/main/java/com/example/triptracker/view/map/AddSpot.kt
app/src/main/java/com/example/triptracker/view/map/AddSpotTakePictures.kt
app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
app/src/main/java/com/example/triptracker/viewmodel/CameraPermissions.kt
gradle/libs.versions.toml

This PR will bring some changes to the UI : 
- It will allow to click on the profile picture of other users in the app in order to display it in a more convenient format.
<image src = https://github.com/EPFL-SwEnt-2024-LaStartUp/TripTracker/assets/79469048/7a2a93fc-3538-4e70-b870-573c380f6ab5 width = 300>
- AddSpot allows to take picture directly in the app and store them in the gallery. The user is then able to pick the taken pictures with the photopicker
<image src = https://github.com/EPFL-SwEnt-2024-LaStartUp/TripTracker/assets/79469048/9c563658-762a-4618-8d0a-5b06c5e84887 width =300>
- It will ask for Camera permissions on launch of the app so that pictures can be taken in the AddSpot screen and will also reask permissions when the camera is launched even it not accepted.
- Test for …

Addspot update

---

app/src/main/java/com/example/triptracker/model/geocoder/NominatimApi.kt
app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
app/src/main/java/com/example/triptracker/viewmodel/MapViewModel.kt
app/src/main/java/com/example/triptracker/viewmodel/RecordViewModel.kt
app/src/test/java/com/example/triptracker/NominatimGeocoderTest.kt

This PR add the functionality to save the City and the Country when recording a path, which is helpful later when searching paths based on their location.
For demonstration (not kept in the map screen):

Save the country and city location when recording a path

---

app/src/androidTest/java/com/example/triptracker/userProfile/DropDownSelectorTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileEditScreenTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileTest.kt
app/src/androidTest/java/com/example/triptracker/userProfile/UserViewTest.kt
app/src/main/java/com/example/triptracker/model/profile/UserProfile.kt
app/src/main/java/com/example/triptracker/model/repository/UserProfileRepository.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileOverview.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileUtils.kt
app/src/main/java/com/example/triptracker/view/profile/subviews/DropDownSelector.kt
app/src/main/java/com/example/triptracker/view/profile/subviews/ProfileCounts.kt
app/src/main/java/com/example/triptracker/view/profile/subviews/ProfileInfoView.kt

**Corresponding issue : #235** 
With this PR the user will now be able to personnalise his/her profile further than before.
The following files have been modified to create the necessary backend :
- `UserProfile` : added the interests/travel style/languages parameters 
- `UserProfileRepository` : added function to add empty lists for the new parameters to the users already created 
- `UserProfileUtils` : added enumerations for the difference interests/travel style/languages that the user can select
The following views have been modified/added to allow the user to reflect the backend changes : 
- `UserProfileEditScreen` : the edit view now allows the user to select interests/travel style/languages to personnalise his/her profile
- `DropDownSelector` : a composable used to display the …

Profile refinements

---

app/build.gradle.kts
app/src/main/java/com/example/triptracker/model/repository/ImageRepository.kt
app/src/main/java/com/example/triptracker/view/map/AddSpot.kt
app/src/main/java/com/example/triptracker/view/map/AddSpotTakePictures.kt
app/src/main/java/com/example/triptracker/view/map/PictureUtils.kt
app/src/test/java/com/example/triptracker/PictureUtilsTest.kt
gradle/libs.versions.toml

Pictures are now uploaded to the storage in a resized cost efficient format that allows to save space on the phone and the DB. 
This will make the app faster since the pictures will be downloaded faster. The demo will be better and the download of a path will be also improved

Pictures uploaded to storage are now much smaller and efficient

---

app/build.gradle.kts
app/src/androidTest/java/com/example/triptracker/view/NavigationBarTest.kt
app/src/main/java/com/example/triptracker/model/repository/ItineraryRepository.kt
app/src/main/java/com/example/triptracker/view/NavigationBar.kt
app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
app/src/main/java/com/example/triptracker/view/profile/UserProfileScreenUtils.kt
app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt

This PR will : 
- Fix the refresh of the My trips UI once a trip is deleted. Now the delete triggers a recomposition of the screen and display the changes in real time.
- When navigating on subscreens of the profile screen and then changing to maps / record or home, returning back to the profile reloads the same screen as it was left. Now on click on the profile it will always show the start screen.

Refresh the My Trips screen when a path is deleted. Fix the navigation in the profile screens

---

app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt

This PR brings back the home package coverage to 81%.
Changes:
- Comments are added on each test
- 4 new tests:
- `SwipeLeftWithItineraries` swipes left on home pager with itineraries in following and trending pages
- `testWithBooleanFalseHomeScreen` to reach uncovered lines 
- `clickOnDropDownMenuDisplaysFilters` clicks on the dropdown in search bar and selects username filter
- `itineraryItemDisplayed` checks if itinerary item is displayed when in search bar

Home Tests 

---

app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt

This PR makes changes to the UI to look cleaner and more correct.
It addresses issues #260 #272 #273 
The changes includes :
1. [Fixed splitting filter text, taking into account screen height and width](https://github.com/EPFL-SwEnt-2024-LaStartUp/TripTracker/commit/91eefab421ab4fe3d50f91131f029f481fe6f9c7) + Increased width of search dropdown so that it covers / hides  the itineraries
<br/>
<br/>
2. [Fixed description display bug](https://github.com/EPFL-SwEnt-2024-LaStartUp/TripTracker/commit/bcdc2e4774fcf9f493624f8a7ee03dd5064964bf)
<br/>
<br/>
3. [Exchanged description with title in the popup](https://github.com/EPFL-SwEnt-2024-LaStartUp/TripTracker/commit/8da827c8db1da69b6e920500550efce6f85a0408)

Home fixes & others 🌸

---

app/src/main/java/com/example/triptracker/view/OfflineScreen.kt

This PR update the offline screen to resemble the Figma, adjust to all screen sizes and include the dark mode.
**Before:**
**After:**

Update the offline screen

---

app/src/androidTest/java/com/example/triptracker/map/MapOverviewTest.kt
app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
app/src/main/java/com/example/triptracker/view/profile/UserView.kt

This PR fixes #289. The screens that did not take into account privacy settings before now take privacy settings into account before showing itineraries.
- When looking at someone else's profile, the itineraries will show up only if this person's privact settings allow it
- If the setttings don't allow it, you'll see the profile as if this user didn't register any trips, it doesn't tell you that their privacy settings don't allow it
- Itineraries will only show up on the Map if the owner's privacy settings allow it

Map screen privacy

---

app/src/androidTest/java/com/example/triptracker/e2eTest.kt

The long awaited E2E is finally here, this is the first part testing the profile screen.
This PR introduces a comprehensive end-to-end (E2E) test for the profile screen navigation flow within the app. The test ensures that users can seamlessly navigate through various profile-related screens, perform actions, and return to the profile overview screen, verifying the integrity and usability of the navigation.
Instead of mocking with mockk, it was simpler to create a NavHost and perform actual navigation through parts of the app to test that everything is working well.

End2End Test Pt. 1

---

app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt

This PR fixes a small UI issue :

Fixed Dark Mode in Home Screen
