EPFL-SwEnt-2024-LaStartUp/TripTracker

- app/src/main/java/com/example/triptracker/MainActivity.kt
- app/src/main/java/com/example/triptracker/authentication/GoogleAuthenticator.kt
- app/src/main/java/com/example/triptracker/view/LoginScreen.kt
Added logic to enable user to sign out from account and go back to login screen.
Slight change in UI for the profile screen
> Allow user to sign out from profile page

- app/build.gradle.kts
- gradle/libs.versions.toml
Updated the build.grade.kts app file to add sonarCloud and added some parts for the Jacoco test report
> Added solarCloud

- app/src/main/java/com/example/triptracker/MainActivity.kt
- app/src/main/java/com/example/triptracker/model/repository/ItineraryRepository.kt
- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
- app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
- app/src/main/java/com/example/triptracker/viewmodel/MapViewModel.kt
These changes include:
1. Not giving a map as argument to DisplayItinerary in HomeScreen.kt which was silly. Now just have to give the itinerary and the navigation to know where to go.
2. Removed a function from the ItineraryRepository and several from the HomeViewModel
3. Moved all in a home package that contains useful functions to display the itinerary
> Refactored the HomeViewModel to adapt to MapViewModel.

- app/src/androidTest/java/com/example/triptracker/itinerary/ItineraryListTest.kt
- app/src/androidTest/java/com/example/triptracker/itinerary/ItineraryTest.kt
- app/src/main/java/com/example/triptracker/model/itinerary/ItineraryList.kt
- app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
Tests implemented for the following two classes:
Itinerary : the data class representing an itinerary
ItineraryList : data class representing a list of itineraries and providing functions to filter, get itineraries based on their uid or locations, and get and set the list (+add itineraries)
The ItineraryList class was also modified
ItineraryList now has more functions to modify the list and the list property is now set to private
HomeViewModel : small modification to use the getter function of ItineraryList and not directly the list property as it is now set to private
> Implemented Itinerary model tests

- app/src/main/java/com/example/triptracker/MainActivity.kt
- app/src/main/java/com/example/triptracker/navigation/LocationUtils.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
> Bugfix maps screen location permission

- app/src/androidTest/java/com/example/triptracker/map/RecordViewModelTest.kt
- app/src/main/java/com/example/triptracker/viewmodel/RecordViewModel.kt
This pull request includes changes to the RecordViewModel class and its corresponding unit tests in the RecordViewModelTest class. The changes are aimed at improving the functionality and reliability of the recording feature in the application
1.  In RecordViewModel.kt, the isRecording() function has been updated to check both the start time and end time. This ensures that the function only returns true if a recording is currently ongoing (i.e., the start time has been set but the end time has not).
2.  In RecordViewModelTest.kt, various unit tests have been added to test the functionality of the RecordViewModel. 
_Please review these changes and let me know if you have any feedback or questions._
> Improve RecordViewModel and its Unit Tests

- app/src/main/java/com/example/triptracker/view/profile/UserProfileOverview.kt
Fixed the duplicate code issue, previous pr should not have been merged already, this should have been a new commit on previous PR
> Duplicate Code fix

- app/build.gradle.kts
Associated issue: #84 
What was done:
- fix the imports in `build.gradle.kts` according to https://mockk.io/
- test that now it's working now by mocking the Navigation class
> Fix the dependency imports for MockK library

- app/src/androidTest/java/com/example/triptracker/itinerary/MockItineraryList.kt
- app/src/androidTest/java/com/example/triptracker/map/MapPopupTest.kt
- app/src/main/java/com/example/triptracker/model/location/Pin.kt
- app/src/main/java/com/example/triptracker/model/repository/ItineraryRepository.kt
- app/src/main/java/com/example/triptracker/view/map/AddSpot.kt
- app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
This changes how the DB stores the data for pinned places. Instead of a string as a url we now have the ability to store a list of uri's so that multiple pictures can be uploaded per spot
> This changes the DB for pinned places

- app/src/main/java/com/example/triptracker/view/map/MapElements.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
This will allow to pass a LatLng (corresponding to the start of a path) so that the map will first be centered on this point when loading the MapOverview.
For this you simply need to add the startLocation parameter to the call of the MapOverview and it needs to be different from the DEFAULT_LOCATION
> Center Map on given location

- app/src/androidTest/java/com/example/triptracker/userProfile/MockUserList.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileViewModelTest.kt
- app/src/main/java/com/example/triptracker/model/profile/UserProfile.kt
- app/src/main/java/com/example/triptracker/view/profile/FriendListView.kt
- app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
The followers and following properties are now of type List<String> instead of List<UserProfile> and contains the mail of the other followers/following. This will make it easier to store. 
I also added a function getUserProfileFromDb that takes an email and returns the corresponding profile. It will be useful to fetch the data about the followers and following.
> Udpated the follower and following properties

- app/src/androidTest/java/com/example/triptracker/itinerary/ItineraryListTest.kt
- app/src/main/java/com/example/triptracker/model/itinerary/ItineraryList.kt
- app/src/main/java/com/example/triptracker/navigation/LocationUtils.kt
- app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
This will allow the recording location to be saved as the mean of all the latitude longitude points of the path (temporary)
This will also allow the path to be displayed if they have a recorded latLng that is within the bounds of the screen
> Changed how the paths are displayed on the map

- app/src/androidTest/java/com/example/triptracker/map/MapPopupTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFollowersTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFollowingTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileViewModelTest.kt
- app/src/main/java/com/example/triptracker/model/repository/UserProfileRepository.kt
- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
- app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
- app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
This PR improves the search bar usability in the home screen.
It adds the following aspects to the app
- Adds examples on how to use the filters
- Implements the username search since last change to usermail in Itinerary 
Bug fix : addresses bug #116
> Search bar fixes

- app/src/androidTest/java/com/example/triptracker/userProfile/MockUserList.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFollowersTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFollowingTest.kt
- app/src/main/java/com/example/triptracker/MainActivity.kt
- app/src/main/java/com/example/triptracker/model/profile/UserProfileList.kt
- app/src/main/java/com/example/triptracker/model/repository/ImageRepository.kt
- app/src/main/java/com/example/triptracker/model/repository/UserProfileRepository.kt
- app/src/main/java/com/example/triptracker/view/Navigation.kt
- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
- app/src/main/java/com/example/triptracker/view/profile/FriendListView.kt
- app/src/main/java/com/example/triptracker/view/profile/FriendSearchBar.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileFollowers.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileFollowing.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileOverview.kt
- app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
For the corresponding issue, see #129 
Both the `UserProfileFollowers` and `UserProfileFollowing` views now feature a search bar to easily find a given follower or following. The search bar looks for correspondance between the query and the name or surname or username of followers/following.
The search bar is implemented in the `FriendSearchBar` composable
The user profile of the current user is retrieved from the database based on the email available in the whole application.
> Followers following update

- app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileSettingsTest.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileSettings.kt
This PR adds the test for the user profile settings screen.
> User profile settings tests

- app/src/main/java/com/example/triptracker/view/LoginScreen.kt
Added functionality so that on signing in, a new UserProfile is created in the database
For now initializes the name, username, surname values to the google username, initalizes the other attributes to the equivalent google one
> Profile Works with new users

- app/src/androidTest/java/com/example/triptracker/authentication/LoginTest.kt
- app/src/androidTest/java/com/example/triptracker/authentication/LoginTestResults.kt
> Profile new user

- app/src/androidTest/java/com/example/triptracker/map/AddSpotTest.kt
Commented test that makes ci crash
> test comment for ci

- app/src/androidTest/java/com/example/triptracker/map/RecordTest.kt
- app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
This pull request includes the following changes:
- Modified `RecordScreen.kt` to include functionality for handling close button clicks when in description
- Added UI tests for `RecordScreen` in `RecordTest.kt`.
- Added UI tests for `testClickOnCloseWhenInDescription()` and `testRecordTextIsDisplayed()` in `RecordTest.kt`.
- Modified `RecordScreen.kt` to include logic for handling close button clicks and displaying record text.
- Ensured that UI tests pass successfully.
> fix UI + add close button when in description

- app/src/androidTest/java/com/example/triptracker/map/MapOverviewTest.kt
- app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/MockUserList.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFavouritesTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileMyTripsTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileTest.kt
- app/src/main/java/com/example/triptracker/MainActivity.kt
- app/src/main/java/com/example/triptracker/model/profile/UserProfile.kt
- app/src/main/java/com/example/triptracker/model/repository/UserProfileRepository.kt
- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileFavourites.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileMyTrips.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileScreenUtils.kt
- app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
- app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
This pull request includes the following changes:
- Modified `UserProfile.kt` to include a new parameter for favorites path
- Modified  `UserProfileFavourites.kt` to display the favorites trips of the current user
- Added `UserProfileUtils` to don't duplicate code in `UserProfileFavourites` and `UserProfileMyTrips`
- Modified `HomeUtils` to display the star and handle pressing on it.
- Modified `UserProfileViewModel` to add a remove and add  favourites path to the db
- Modified `MainActivity` to pass the ambiant profile each time a class need it for displaying the pop of an itinerary
_Other changes are just for adapting code to this new features_
This PR added test to the classes I modified or added to ensure a good coverage !
> Favourite pathv2

- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileScreenUtils.kt
- app/src/main/java/com/example/triptracker/view/profile/UserView.kt
This will fix the bug where in the homeview the showed profile for a path is always the same.
Now the ambientuserprofile is used in order to display the favorites and the profile for each user is fetched to show the owner of the path.
> Bugfix : always the same profile showing in the homeView

- app/src/androidTest/java/com/example/triptracker/authentication/LoginTest.kt
- app/src/androidTest/java/com/example/triptracker/authentication/LoginTestResults.kt
Thanks to the work of @cleorenaud the Firestore bug is no more. In this PR I uncommented and adjusted the Login Tests that had to be commented out in the previous Milestone.
Had to adjust the parameter for the UserProfile.
> Login Tests adjusted

- app/src/androidTest/java/com/example/triptracker/map/MapOverviewTest.kt
- app/src/main/java/com/example/triptracker/MainActivity.kt
- app/src/main/java/com/example/triptracker/view/map/AddSpot.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
Made the picture pop up scrollable.
Changed complexity of code and refactored unused arguments.
> Reduced code complexity and removed unused code

- app/src/androidTest/java/com/example/triptracker/map/AddSpotTest.kt
- app/src/androidTest/java/com/example/triptracker/screens/userProfile/UserProfileEditScreenTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserViewTest.kt
Adding special cases tests of uncovered lines to achieve 80%.
Current changes: AddSpot, UserView. AddSpot tests were already done, removed them.
> Increase Coverage Tests

- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
This PR addresses the feedback given in M2 to give a more appealing look to the Home Screen by including the pictures from the pins put by the user
UI now looks like this:
*Note:*
*1. If the itinerary doesn't have any pictures, it will keep the previous box size, otherwise it gets bigger to accommodate for the images.*
*2. I didn't have to modify tests, still have 90% coverage in `HomeUtils.kt`*
> Include pin images in Home Screen

- app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
- app/src/main/java/com/example/triptracker/viewmodel/UserProfileViewModel.kt
**Associated issue: #196**
This PR updates the code of `UserProfileEditScreen.kt` and `UserProfileViewModel.kt` according to the issue (complexity and moving backend to VM).
Some visual improvements to the edit screen were added so to resemble more the Figma design (small orange circle, vertical spacers, etc).
> Refactoring of user profile edit screen

- app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
Username Bug:
The Username is now limited to 30 characters to avoid any overflow errors in parts of the app.
Date Picker Bug:
Date can now only be picked in the past.
> Profile Screen Bug Fixes

- app/src/main/java/com/example/triptracker/view/profile/UserView.kt
- app/src/main/java/com/example/triptracker/view/profile/subviews/ProfileCounts.kt
Fixed a bug allowing the user to navigate to its followers/following list by clicking on the followers/following button on the screen displaying the profile of another user.
> Updated the UserView

- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
- app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
This PR lowers aims to lower the complexity of three classes by refactoring the code:
- `RecordScreen.kt`
- `MapPopups.kt`
- `MapOverview.kt`.
Important note: since there was an issue when testing because of a nullpointer for the application context that was resolved in the `trending-tests` branch, this branch is itself a branch of `trending-tests` and not main.
As a result, before merging this one, we should wait for Théo's PR with the new Trending tab being merged.
In the very worst case, we can only isolate the code for the three classes above only so to merge it with master in an other PR.
> Lower complexity

- app/src/main/java/com/example/triptracker/view/profile/UserProfileOverview.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileUtils.kt
- app/src/main/java/com/example/triptracker/view/profile/subviews/ProfileCounts.kt
- app/src/main/java/com/example/triptracker/view/profile/subviews/ProfileInfoView.kt
This PR updates a few visual components of the profile in order to make it look better for big phones and just cleaner in a general way.
- Updated the font size of the bigNumberStyle, categoryTextStyle, secondaryTitleStyle, secondaryContentStyle
- Tweaked the way the follower, following and myTrips count were arranged to center it bette
- Fixed the shadow of the profile picture so that it is properly aligned with the profile picture
- Changed the friends view to find friends and changed the button icon
> Profile UI Update

- app/src/main/java/com/example/triptracker/model/repository/ItineraryRepository.kt
- resources/SCRUM Board - Sprint View M3.tsv
> Added TSV + var to val

- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
- app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
This pull request includes a series of updates to the `MapOverview.kt`, `MapPopups.kt`, and `RecordScreen.kt` files to improve the user interface and user experience of the Trip Tracker application. It fixes the bug of the save button and the Start Screen
---
1. `app/src/main/java/com/example/triptracker/view/map/MapOverview.kt`
2. `app/src/main/java/com/example/triptracker/view/map/MapPopups.kt`
3. `app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt`
> Bug fix StartScreen

- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileEditScreenTest.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
> 80coverage

- app/src/androidTest/java/com/example/triptracker/map/MapPopupTest.kt
- app/src/androidTest/java/com/example/triptracker/map/RecordTest.kt
Quick test in recordscreen that should get us the coverage
> 80% Coverage (fingers crossed)

- app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/FriendSearchBarTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/ProfileCountsTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileFriendsTest.kt
- app/src/androidTest/java/com/example/triptracker/userProfile/UserViewTest.kt
- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileScreenUtils.kt
- app/src/main/java/com/example/triptracker/view/profile/UserView.kt
- app/src/main/java/com/example/triptracker/view/profile/subviews/FriendSearchBar.kt
- app/src/main/java/com/example/triptracker/view/profile/subviews/ProfileCounts.kt
**Corresponding issue : #250** 
With this PR some new tests have been implemented to slightly increase the code coverage and some unused parameters have been removed.
The following tests have been added :
- `FriendSearchBarTest` : ensured that the elements of the search bar are correctly displayed and that the delete button works as intended
- `ProfileCountsTest` : ensured that the elements displayed are correct and that the navigation works as intended
The following tests have been modified : 
- `UserProfileFriendTest` : added check for the search bar and check for the navigation
- `UserViewTest` : added check for the navigation
The following views have been modified : 
- `FriendSearchBar` : changed some of the tests tags
- `ProfileCounts` changed some of the tests tags
Some unused …
> User profile new tests

- app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
- app/src/androidTest/java/com/example/triptracker/screens/home/HomeViewScreen.kt
- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileScreenUtils.kt
- app/src/main/java/com/example/triptracker/view/profile/UserView.kt
- adds the feature to be able to click on the username to access the profile. 
- correct the UI to match the figma (add shadow, improve padding, ...)
- Fix the star that was not display
> Username into profile

- app/src/androidTest/java/com/example/triptracker/map/AddSpotCameraTest.kt
- app/src/androidTest/java/com/example/triptracker/view/NavigationBarTest.kt
- app/src/main/java/com/example/triptracker/view/map/AddSpotTakePictures.kt
This PR adds a back button on the top right corner of the camera screen and also tests for it
> Back button for camera screen

- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
- Refonte du cancel trip tab en light et dark mode.
- Adaptation du home screen au Dark Mode
> Dark Mode updates

- app/build.gradle.kts
- app/src/androidTest/java/com/example/triptracker/userProfile/UserProfileEditScreenTest.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileEditScreen.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileSettings.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileUtils.kt
- app/src/main/java/com/example/triptracker/view/profile/subviews/FriendListView.kt
**Corresponding issues : #258 and #261** 
With this PR, the application UI have been slightly modified in the user profile section of the app, to make it more intuitive and ensures it looks good on even more phones than before
The following views have been modified:
- `UserProfileEditScreen` : updated the layout of the screen to make it more intuitive
- `UserProfileSetting` : updated the size of the buttons to better fit on more phones
- `FriendListView` : updated the font size to better fit on more phones
The following test has been updated :
- `UserProfileEditScreenTest` : added a test to ensure that the scroll down arrow works as intended and corrected some old tests by adding a scroll action to go to the node
The `app/build.gradle.kts` file has been modified just to correct the layout
> Update edit user screen + small UI modifications

- app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
- app/src/main/java/com/example/triptracker/view/map/RecordScreen.kt
- app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
This PR add the followings : 
- New feature 🔥 : swipe down to refresh
- New test for this
- Fix record screen bug with the font 
- Rework of the structure of the UI in the StartScreen to adapt to all phone
_(and merging conflict...)_
> Pull refresh 

- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
- app/src/main/java/com/example/triptracker/viewmodel/HomeViewModel.kt
This PR add the following : 
- Pull refresh now working for following 
- Pull refresh now working when it's empty and we swipe down
- Start Screen position of the image is lower to keep space for text
> Fix bugs : PullRefresh following + Start Screen 🌹🌷 

- app/src/androidTest/java/com/example/triptracker/screens/home/HomeTest.kt
- app/src/main/java/com/example/triptracker/model/profile/UserProfile.kt
- app/src/main/java/com/example/triptracker/model/repository/UserProfileRepository.kt
- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
- app/src/main/java/com/example/triptracker/view/map/MapPopups.kt
- app/src/main/java/com/example/triptracker/view/profile/UserProfileSettings.kt
This PR adds a really funky flower mode to the app
Here's how it looks:
> I can buy myself flowers 🌸🌷🌹🌺🌻🌼 - Flowers mode

- app/src/main/java/com/example/triptracker/view/home/HomeUtils.kt
This will reduce the complexity of the HomeUtils.kt class under 50.
> Reduced complexity of HomeUtils.kt

- app/src/main/java/com/example/triptracker/view/profile/UserProfileSettings.kt
- app/src/main/java/com/example/triptracker/view/profile/subviews/FriendListView.kt
- app/src/main/java/com/example/triptracker/view/theme/Color.kt
This PR updates the color scheme for the primary and secondary buttons to enhance readability. The new colors provide better contrast and comply with accessibility standards.
- Primary Button: Background changed to #0056b3, text color changed to #ffffff
- Secondary Button: Background changed to #6c757d, text color changed to #ffffff
- Verified the new colors visually in the browser.
- Ensured the hover states are working correctly.
> Polishing app - update buttons

- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
This PR modularises and reduces even more the complexity in the `HomeScreen.kt`
The code is also now fully documented 
*Note: we can't know in advance by how much the complexity is reduced until being merged in master. This is why there is this second PR that complements #291*
> Reduced complexity in `HomeScreen.kt`

- app/src/main/java/com/example/triptracker/view/home/HomeScreen.kt
- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
Fixed the bug showed in #290 where if your privacy was different than public, you could not see your own trips in the Home Screen or the Map Screen
> Fixed a bug where you could not see your own path

- app/src/main/java/com/example/triptracker/view/map/MapOverview.kt
An if clause was ccausing the app to crash. This issue emerged when doing refactoring
> BugFix of the mapoverview
